services:
  - type: web
    name: hermate-backend
    env: python
    region: singapore
    plan: free

    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

    runtime: python3.10

    envVars:
      - key: GOOGLE_API_KEY
        sync: false
